/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FoaieMatricola;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import static javax.swing.JOptionPane.YES_OPTION;


/**
 *
 * @author Mario
 */
public class FoaieMatricola extends javax.swing.JFrame {
    
    private static final String username="root";
    private static final String password="Aa2210@";
    private static final String dataConn="jdbc:mysql://localhost:3306/foaiematricola";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;


    

    /**
     * Creates new form FoaieMatricola
     */
    public FoaieMatricola() {
        initComponents();
        updateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //===========================================================function declaration======================================================
    public void updateDB(){
        int q,i;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("Select * from foaiematricola");
            
            rs =pst.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();
            
            q = StData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for(i = 1; i <= q; i++){
                    columnData.add(rs.getString("id"));
                    columnData.add(rs.getString("elevid"));
                    columnData.add(rs.getString("prenume"));
                    columnData.add(rs.getString("nume"));
                    columnData.add(rs.getString("adresa"));
                    columnData.add(rs.getString("sex"));
                    columnData.add(rs.getString("telefon"));
                    columnData.add(rs.getString("matematica"));
                    columnData.add(rs.getString("lbRomana"));
                    columnData.add(rs.getString("informatica"));
                    columnData.add(rs.getString("biologie"));
                    columnData.add(rs.getString("istorie"));
                    columnData.add(rs.getString("sport"));
                    columnData.add(rs.getString("engleza"));
                    columnData.add(rs.getString("geografie"));
                }
                    
                    RecordTable.addRow(columnData);

                
            }
            
            
            
            
        }
        
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    }
    
                                              
    
    
    //========================================================================================================================
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnStergere = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnActualizare = new javax.swing.JButton();
        btnResetare = new javax.swing.JButton();
        btnAdaugare = new javax.swing.JButton();
        btnPrintare = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        cboSex = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtElevID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrenume = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNume = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        cboMatematica = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboLbRomana = new javax.swing.JComboBox<>();
        cboBiologie = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboInformatica = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cboEngleza = new javax.swing.JComboBox<>();
        cboIstorie = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cboSport = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cboGeografie = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Foaie Matricola");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 480, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1410, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1310, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1310, 70));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 0), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStergere.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnStergere.setText("Stergere");
        btnStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergereActionPerformed(evt);
            }
        });
        jPanel5.add(btnStergere, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 230, 50));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnExit.setText("Inchide");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel5.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 230, 50));

        btnActualizare.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnActualizare.setText("Actualizare");
        btnActualizare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizareActionPerformed(evt);
            }
        });
        jPanel5.add(btnActualizare, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 210, 50));

        btnResetare.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnResetare.setText("Resetare");
        btnResetare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetareActionPerformed(evt);
            }
        });
        jPanel5.add(btnResetare, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 240, 50));

        btnAdaugare.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAdaugare.setText("Adaugare");
        btnAdaugare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugareActionPerformed(evt);
            }
        });
        jPanel5.add(btnAdaugare, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 50));

        btnPrintare.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnPrintare.setText("Printare");
        btnPrintare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintareActionPerformed(evt);
            }
        });
        jPanel5.add(btnPrintare, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 200, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1390, 70));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 0), 4));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "elev id", "prenume", "nume", "adresa", "sex", "telefon mobil", "matematica", "limba romana", "informatica", "biologie", "geografie", "istorie", "sport", "engleza"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 480));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 850, 500));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 0), 4));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Telefon");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 70, -1));

        txtTelefon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel7.add(txtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 150, -1));

        cboSex.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masculin", "feminin" }));
        jPanel7.add(cboSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Elev ID");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        txtElevID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel7.add(txtElevID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 340, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Prenume");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

        txtPrenume.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel7.add(txtPrenume, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 340, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Nume");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, -1));

        txtNume.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel7.add(txtNume, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 340, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Adresa");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));

        txtAdresa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel7.add(txtAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 340, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Sex");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 260));

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 260));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 260));

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 260));

        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 260));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 260));

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 260));

        cboMatematica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboMatematica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promovat", "Nepromovat" }));
        jPanel8.add(cboMatematica, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Matematica");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Lb romana");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, 30));

        cboLbRomana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboLbRomana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promovat", "Nepromovat" }));
        jPanel8.add(cboLbRomana, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, 30));

        cboBiologie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboBiologie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promovat", "Nepromovat" }));
        jPanel8.add(cboBiologie, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Biologie");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 90, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Informatica");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 110, 20));

        cboInformatica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboInformatica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promovat", "Nepromovat" }));
        jPanel8.add(cboInformatica, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, 30));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 260, 210));

        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Sport");
        jPanel16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 80, 30));

        cboEngleza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboEngleza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promovat", "Nepromovat" }));
        jPanel16.add(cboEngleza, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, 30));

        cboIstorie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboIstorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promovat", "Nepromovat" }));
        jPanel16.add(cboIstorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 140, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Istorie");
        jPanel16.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Engleza");
        jPanel16.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 80, 50));

        cboSport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboSport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promovat", "Nepromovat" }));
        jPanel16.add(cboSport, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Geografie");
        jPanel16.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 110, 30));

        cboGeografie.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboGeografie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promovat", "Nepromovat" }));
        jPanel16.add(cboGeografie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, 30));

        jPanel7.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 240, 210));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1410, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetareActionPerformed
            
            txtElevID.setText("");
            txtPrenume.setText("");
            txtNume.setText("");
            txtAdresa.setText("");
            cboSex.setSelectedIndex(0);
            txtTelefon.setText("");
            cboMatematica.setSelectedIndex(0);
            cboLbRomana.setSelectedIndex(0);
            cboInformatica.setSelectedIndex(0);
            cboBiologie.setSelectedIndex(0);
            cboIstorie.setSelectedIndex(0);
            cboSport.setSelectedIndex(0);
            cboEngleza.setSelectedIndex(0);
            cboGeografie.setSelectedIndex(0);
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
    }//GEN-LAST:event_btnResetareActionPerformed

    private void btnStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergereActionPerformed
        
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();
         
         try{
             int id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
             
             int deleteItem = JOptionPane.showConfirmDialog(null, "Confirmati daca doriti sa stergeti inregistrarea", "Atentie",JOptionPane.YES_NO_OPTION);
                     
             if(deleteItem ==  YES_OPTION){
                 
          
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("delete from foaiematricola where id=?");
            
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Inregistrarea elevului stearsa");
            updateDB();
            
            txtElevID.setText("");
            txtPrenume.setText("");
            txtNume.setText("");
            txtAdresa.setText("");
            cboSex.setSelectedIndex(0);
            txtTelefon.setText("");
            cboMatematica.setSelectedIndex(0);
            cboLbRomana.setSelectedIndex(0);
            cboInformatica.setSelectedIndex(0);
            cboBiologie.setSelectedIndex(0);
            cboIstorie.setSelectedIndex(0);
            cboSport.setSelectedIndex(0);
            cboEngleza.setSelectedIndex(0);
            cboGeografie.setSelectedIndex(0);
             }

            
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoaieMatricola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.err.println(ex);

        } 
        
    }//GEN-LAST:event_btnStergereActionPerformed
private JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Doriti sa inchideti?","FoaieMatricola",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAdaugareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugareActionPerformed
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("insert into foaiematricola(elevid,prenume,nume,adresa,"
                    + "sex,telefon,matematica,lbRomana,informatica,biologie,istorie,sport,engleza,geografie)values"
                    + "(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, txtElevID.getText());
            pst.setString(2, txtPrenume.getText());
            pst.setString(3, txtNume.getText());
            pst.setString(4, txtAdresa.getText());
            pst.setString(5, (String)cboSex.getSelectedItem());
            pst.setString(6, txtTelefon.getText());
            pst.setString(7, (String)cboMatematica.getSelectedItem());
            pst.setString(8, (String)cboLbRomana.getSelectedItem());
            pst.setString(9, (String)cboInformatica.getSelectedItem());
            pst.setString(10, (String)cboBiologie.getSelectedItem());
            pst.setString(11, (String)cboIstorie.getSelectedItem());
            pst.setString(12, (String)cboSport.getSelectedItem());
            pst.setString(13, (String)cboEngleza.getSelectedItem());
            pst.setString(14, (String)cboGeografie.getSelectedItem());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Inregistrarea elevului adaugata");
            updateDB();
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoaieMatricola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            //System.err.println(ex);
            java.util.logging.Logger.getLogger(FoaieMatricola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnAdaugareActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();
         txtElevID.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
         txtPrenume.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
         txtNume.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
         txtAdresa.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
         cboSex.setSelectedItem(RecordTable.getValueAt(SelectedRows, 5).toString());
         txtTelefon.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
         cboMatematica.setSelectedItem(RecordTable.getValueAt(SelectedRows, 7).toString());
         cboLbRomana.setSelectedItem(RecordTable.getValueAt(SelectedRows, 8).toString());
         cboInformatica.setSelectedItem(RecordTable.getValueAt(SelectedRows, 9).toString());
         cboBiologie.setSelectedItem(RecordTable.getValueAt(SelectedRows, 10).toString());
         cboIstorie.setSelectedItem(RecordTable.getValueAt(SelectedRows, 11).toString());
         cboSport.setSelectedItem(RecordTable.getValueAt(SelectedRows, 12).toString());
         cboEngleza.setSelectedItem(RecordTable.getValueAt(SelectedRows, 13).toString());
         cboGeografie.setSelectedItem(RecordTable.getValueAt(SelectedRows, 14).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnActualizareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizareActionPerformed
         
         DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();
         
         try{
             int id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("update foaiematricola set elevid =?, prenume=?,"
                    + "nume =?, adresa=?,sex=?,telefon=?,matematica=?,lbRomana=?,informatica=?,biologie=?,istorie=?,sport=?,engleza=?,geografie=? where id=?");
            pst.setString(1, txtElevID.getText());
            pst.setString(2, txtPrenume.getText());
            pst.setString(3, txtNume.getText());
            pst.setString(4, txtAdresa.getText());
            pst.setString(5, (String)cboSex.getSelectedItem());
            pst.setString(6, txtTelefon.getText());
            pst.setString(7, (String)cboMatematica.getSelectedItem());
            pst.setString(8, (String)cboLbRomana.getSelectedItem());
            pst.setString(9, (String)cboInformatica.getSelectedItem());
            pst.setString(10, (String)cboBiologie.getSelectedItem());
            pst.setString(11, (String)cboIstorie.getSelectedItem());
            pst.setString(12, (String)cboSport.getSelectedItem());
            pst.setString(13, (String)cboEngleza.getSelectedItem());
            pst.setString(14, (String)cboGeografie.getSelectedItem());
            pst.setInt(15, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Inregistrarea elevului actualizata");
            updateDB();
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoaieMatricola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.err.println(ex);

        } 
    }//GEN-LAST:event_btnActualizareActionPerformed

    private void btnPrintareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintareActionPerformed
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        }
        
        catch(java.awt.print.PrinterException e){
            System.err.format("No Printer found", e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnPrintareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoaieMatricola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoaieMatricola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoaieMatricola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoaieMatricola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoaieMatricola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizare;
    private javax.swing.JButton btnAdaugare;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrintare;
    private javax.swing.JButton btnResetare;
    private javax.swing.JButton btnStergere;
    private javax.swing.JComboBox<String> cboBiologie;
    private javax.swing.JComboBox<String> cboEngleza;
    private javax.swing.JComboBox<String> cboGeografie;
    private javax.swing.JComboBox<String> cboInformatica;
    private javax.swing.JComboBox<String> cboIstorie;
    private javax.swing.JComboBox<String> cboLbRomana;
    private javax.swing.JComboBox<String> cboMatematica;
    private javax.swing.JComboBox<String> cboSex;
    private javax.swing.JComboBox<String> cboSport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtElevID;
    private javax.swing.JTextField txtNume;
    private javax.swing.JTextField txtPrenume;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
